name: Deploy Portal

on:
  push:
    branches:
      - main
    paths:
      - src/Shark.Fido2.Portal/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build ./src/Shark.Fido2.Portal/Shark.Fido2.Portal.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish ./src/Shark.Fido2.Portal/Shark.Fido2.Portal.csproj --configuration Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CBD5DFC590D14ACE9202522D37830396 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8EA585DEEC46442E892613CCEB318067 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DDCF1762559E40E7817A22116766408C }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-fido2-dev-05'
          slot-name: 'Production'
          package: .
